spring:
  application:
    name: order-service

  kafka:
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      properties:
        delivery-timeout-ms: 120000
        linger-ms: 0
        request-timeout-ms: 30000
        max-in-flight-requests-per-connection: 5
        enable-idempotence: true
      transactional-id: order-producer-transaction
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: order-service
      isolation-level: read_committed
      properties:
        spring.json.trusted.packages: '*'

  data:
    mongodb:
      database: project
      authentication-database: admin
      username: root
      password: root
      host: localhost
      port: 27017
server:
  port: 8072

orders:
  command:
    topic-name: orders-command-topic
  event:
    topic-name: orders-event-topic

inventory:
  command:
    topic-name: inventory-command-topic
